### ISSUE TITLE
pytorch model not found

### ISSUE THREAD

**Issue by zhenglz** [Wublab/Pythia#2]
In this script "pythia/masked_ddg_scan.py",  if you run it out of the Pythia package, it would give an error: 

Traceback (most recent call last):
  File "/share/zheng/apps/Pythia/pythia/masked_ddg_scan.py", line 115, in <module>
    main(args)
  File "/share/zheng/apps/Pythia/pythia/masked_ddg_scan.py", line 87, in main
    torch_model_c = get_torch_model("../pythia-c.pt", device)
  File "/share/zheng/apps/Pythia/pythia/masked_ddg_scan.py", line 25, in get_torch_model
    model.load_state_dict(torch.load(ckpt_path, map_location=torch.device(device)))
  File "/share/zheng/apps/Pythia/python_env/pythia/lib/python3.9/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/share/zheng/apps/Pythia/python_env/pythia/lib/python3.9/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/share/zheng/apps/Pythia/python_env/pythia/lib/python3.9/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '../pythia-c.pt'

It is suggested to provide an explict file path to the model files. 

```
pythia_root_dpath = os.path.dirname(os.path.abspath(__file__))

#Line 87-89:
    torch_model_c = get_torch_model(os.path.join(pythia_root_dpath, "../pythia-c.pt"), device)
    torch_model_p = get_torch_model(os.path.join(pythia_root_dpath, "../pythia-p.pt"), device)
```

**Comment by Wublab** [comment]
thx, updated
